apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-cloudy-station
  name: pod-cloudy-station
  namespace: cloudstation
spec:
  containers:
  - image: nginx
    name: pod-cloudy-station
    resources: {}
  tolerations:  # New line added.
  - key: "cloud-station"  # New line added.
    operator : "Equal"  # New line added.
    value: "true"  # New line added.
    effect: "NoSchedule"  # New line added.
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
